### ISSUE TITLE
mediapipe selfsegmentation

### ISSUE THREAD

**Issue by hsl20130659** [MirrorYuChen/Mediapipe-MNN#2]
大佬，有空搞个mediapipe selfsegmentation MNN版本啊，Python mediapipe这个人像分割接口存在内存泄露，至今没修复，慎用

**Comment by MirrorYuChen** [comment]
有时间搞一个玩玩

**Comment by MirrorYuChen** [comment]
已经添加了哈~

**Comment by hsl20130659** [comment]
大佬，你的工程所有模型都是转成fp16，有float32原始模型吗，还有那个selfsegmentation的模型也是mediapipe自带的那个吗？我看名字是deeplab_v3_fp16.mnn

**Comment by MirrorYuChen** [comment]
原始就是这个，你可以看他的model介绍页

**Comment by MirrorYuChen** [comment]
fp16和fp32只是存储的不一样而已，实际无差哈

**Comment by MirrorYuChen** [comment]
https://developers.google.com/mediapipe/solutions/vision/image_segmenter

**Comment by MirrorYuChen** [comment]
模型是通过运行python版本examples得到的：https://github.com/googlesamples/mediapipe/tree/main/examples/image_segmentation/python

**Comment by MirrorYuChen** [comment]
![image](https://github.com/MirrorYuChen/Mediapipe-MNN/assets/49817428/b531f9d2-4388-43d5-ba79-9cb2cd900d0e)
