### ISSUE TITLE
face detect模型文件都是 blazedface模型转换成的mnn模型吗

### ISSUE THREAD

**Issue by jaaronkot** [MirrorYuChen/Mediapipe-MNN#5]
看了face detect模型有
```
face_detection_full_range_sparse_fp16.mnn
face_detection_lite.mnn
face_detection_short_range_fp16.mnn
```
这些都是使用mediapipe的 Blazeface 模型转换来的吗，测试了下 `face_detection_short_range_fp16.mnn` 在iPhone11Pro上耗时最小 6-7ms，其他两个在 20ms+了

**Comment by MirrorYuChen** [comment]
是的

**Comment by MirrorYuChen** [comment]
原版模型你去官网找一下，然后可以对比一下两个的差异

**Comment by jaaronkot** [comment]
> 原版模型你去官网找一下，然后可以对比一下两个的差异

感谢~，在官网找到 https://ai.google.dev/edge/mediapipe/solutions/vision/face_detector#blazeface_short-range .tflite的模型，不清楚是不是这个

**Comment by MirrorYuChen** [comment]
应该是的

**Comment by jaaronkot** [comment]
谢谢~
